
[workspace]
resolver = '2'
members = ['libs/devfile_schema', 'apps/cli', 'apps/prepare', 'libs/crd']

[profile.release]
lto = true

[workspace.dependencies]
serde = "1.0.219"
serde_json = "1.0.143"
serde_yaml = "0.9.34"
