[package]
name = "prepare"
version = "0.1.0"
edition = "2021"


[dependencies]
reqwest = { version = "0.12.23", features = ["blocking", "json"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
